const customers = [
  { id: 101, name: 'Rahul', city: 'Hyderabad', gender: 'Male' }, { id: 102, name: 'Priya', city: 'Hyderabad', gender: 'Female' },
  { id: 103, name: 'Arjun', city: 'Bangalore', gender: 'Male' }, { id: 104, name: 'Sneha', city: 'Chennai', gender: 'Female' },
  { id: 105, name: 'Imran', city: 'Mumbai', gender: 'Male' }, { id: 106, name: 'Anjali', city: 'Pune', gender: 'Female' },
  { id: 107, name: 'Vikram', city: 'Delhi', gender: 'Male' }, { id: 108, name: 'Sara', city: 'Hyderabad', gender: 'Female' }
];
const drivers = [
  { id: 201, name: 'Ramesh', city: 'Hyderabad', rating: 4.8 }, { id: 202, name: 'Suresh', city: 'Hyderabad', rating: 4.5 },
  { id: 203, name: 'Kiran', city: 'Bangalore', rating: 4.9 }, { id: 204, name: 'Mahesh', city: 'Chennai', rating: 4.2 },
  { id: 205, name: 'Naveen', city: 'Mumbai', rating: 4.7 }, { id: 206, name: 'Ravi', city: 'Pune', rating: 4.4 }, { id: 207, name: 'Ajay', city: 'Delhi', rating: 4.6 }
];
const rideSeeds = [
 ['2025-01-03','08:00','Madhapur','Hitech City',101,201,18.4,400,'UPI','Completed'], ['2025-01-07','09:00','Banjara Hills','Gachibowli',102,202,11.2,350,'Card','Completed'], ['2025-01-10','18:00','Whitefield','MG Road',103,203,14.1,300,'UPI','Completed'], ['2025-01-14','19:00','T Nagar','Airport',104,204,16.5,350,'Cash','Completed'], ['2025-01-18','17:00','Andheri','Bandra',105,205,9.8,250,'UPI','Completed'], ['2025-01-22','20:00','Koregaon Park','Viman Nagar',106,206,7.5,300,'Card','Completed'],
 ['2025-02-02','08:00','Dwarka','Connaught Place',107,207,18,400,'UPI','Completed'], ['2025-02-06','10:00','Madhapur','Hitech City',101,201,6.3,260,'Card','Completed'], ['2025-02-12','18:00','Banjara Hills','Airport',102,202,20.2,340,'UPI','Completed'], ['2025-02-19','21:00','Whitefield','MG Road',103,203,13.6,200,'Cash','Completed'], ['2025-03-04','09:00','T Nagar','Airport',104,204,17.4,360,'UPI','Completed'], ['2025-03-08','16:00','Andheri','Bandra',105,205,8.2,300,'Card','Completed'], ['2025-03-14','18:00','Koregaon Park','Viman Nagar',106,206,6.8,270,'UPI','Completed'], ['2025-03-20','19:00','Dwarka','Connaught Place',107,207,15.5,260,'Cash','Completed'], ['2025-03-27','22:00','Madhapur','Hitech City',108,201,10.5,120,'UPI','Completed'],
 ['2025-04-02','07:00','Banjara Hills','Gachibowli',102,202,12.2,250,'Card','Completed'], ['2025-04-11','11:00','Whitefield','MG Road',103,203,9.4,180,'UPI','Completed'], ['2025-04-18','18:00','T Nagar','Airport',104,204,15.8,250,'Cash','Completed'], ['2025-04-23','18:00','Andheri','Bandra',105,205,8.1,0,'UPI','Cancelled'], ['2025-04-28','20:00','Madhapur','Hitech City',101,201,5.9,0,'Card','Cancelled']
].map((r, index) => ({ id: index + 1, date: r[0], time: r[1], pickup: r[2], drop: r[3], customerId: r[4], driverId: r[5], distance: r[6], fare: r[7], payment: r[8], status: r[9] }));

rideSeeds[0].fare += 560;
const money = (value, decimals = 0) => `₹${value.toLocaleString('en-IN', { minimumFractionDigits: decimals, maximumFractionDigits: decimals })}`;
const byId = (items, id) => items.find(item => item.id === id);
const group = (items, key) => items.reduce((result, item) => { const name = key(item); result[name] = (result[name] || []).concat(item); return result; }, {});
const state = { charts: {}, search: '' };
let currentRides = rides();

function rides() {
  const from = document.querySelector('#from-date')?.value || '2025-01-01'; const to = document.querySelector('#to-date')?.value || '2025-04-30';
  const city = document.querySelector('#city-filter')?.value || 'all'; const status = document.querySelector('#status-filter')?.value || 'all'; const payment = document.querySelector('#payment-filter')?.value || 'all';
  return rideSeeds.filter(ride => { const customer = byId(customers, ride.customerId); return ride.date >= from && ride.date <= to && (city === 'all' || customer.city === city) && (status === 'all' || ride.status === status) && (payment === 'all' || ride.payment === payment); });
}
function render() {
  currentRides = rides(); const completed = currentRides.filter(r => r.status === 'Completed'); const cancelled = currentRides.filter(r => r.status === 'Cancelled');
  document.querySelector('#kpis').innerHTML = [['Total rides', currentRides.length, 'All booking statuses', 'blue'], ['Completed rides', completed.length, `${currentRides.length ? Math.round(completed.length / currentRides.length * 100) : 0}% completion rate`, 'green'], ['Cancelled rides', cancelled.length, 'Needs attention', 'coral'], ['Cancellation rate', `${currentRides.length ? (cancelled.length / currentRides.length * 100).toFixed(1) : '0.0'}%`, 'Target below 8%', 'yellow'], ['Total revenue', money(completed.reduce((sum, r) => sum + r.fare, 0)), 'Completed rides only', 'ink'], ['Average fare', money(completed.length ? completed.reduce((sum, r) => sum + r.fare, 0) / completed.length : 0, 2), `${completed.length ? (completed.reduce((sum, r) => sum + r.distance, 0) / completed.length).toFixed(2) : '0.00'} km avg distance`, 'blue']].map(item => `<article class="kpi-card ${item[3]}"><span>${item[0]}</span><strong>${item[1]}</strong><small>${item[2]}</small></article>`).join('');
  renderTables(completed); renderInsights(completed, cancelled); renderCharts(currentRides, completed); document.querySelector('#ride-count').textContent = `${currentRides.length} records`; document.querySelector('#peak-hour').textContent = peakHour(currentRides);
}
function renderTables(completed) {
  const driverGroups = group(completed, r => r.driverId); const driverRows = drivers.map(d => ({ ...d, rides: (driverGroups[d.id] || []).length, revenue: (driverGroups[d.id] || []).reduce((s, r) => s + r.fare, 0) })).sort((a, b) => b.revenue - a.revenue);
  document.querySelector('#driver-body').innerHTML = driverRows.map((d, i) => `<tr class="clickable"><td><b class="rank rank-${i + 1}">${i + 1}</b></td><td><strong>${d.name}</strong><small class="sub">#${d.id}</small></td><td>${d.city}</td><td>${d.rating.toFixed(2)} <span class="star">★</span></td><td>${d.rides}</td><td class="align-right"><strong>${money(d.revenue)}</strong></td></tr>`).join('');
  const customerGroups = group(completed, r => r.customerId); const customerRows = customers.map(c => ({ ...c, rides: (customerGroups[c.id] || []).length, revenue: (customerGroups[c.id] || []).reduce((s, r) => s + r.fare, 0) })).sort((a, b) => b.revenue - a.revenue);
  document.querySelector('#customer-body').innerHTML = customerRows.map((c, i) => `<tr><td><b class="rank rank-${i + 1}">${i + 1}</b></td><td><strong>${c.name}</strong></td><td>${c.city}</td><td>${c.rides}</td><td class="align-right"><strong>${money(c.revenue)}</strong></td></tr>`).join('');
  const routeGroups = group(currentRides, r => `${r.pickup} → ${r.drop}`); document.querySelector('#route-body').innerHTML = Object.entries(routeGroups).sort((a, b) => b[1].length - a[1].length).slice(0, 8).map(([route, rows]) => `<tr><td><strong>${route}</strong></td><td>${rows.length}</td><td>${money(rows.reduce((s, r) => s + r.fare, 0) / rows.length)}</td><td>${(rows.reduce((s, r) => s + r.distance, 0) / rows.length).toFixed(1)} km</td></tr>`).join('');
  const search = state.search.toLowerCase(); const filtered = currentRides.filter(r => `${r.id} ${r.date} ${r.pickup} ${r.drop} ${byId(customers, r.customerId).name} ${byId(drivers, r.driverId).name}`.toLowerCase().includes(search)); document.querySelector('#ride-body').innerHTML = filtered.map(r => `<tr><td>#${String(r.id).padStart(4, '0')}</td><td>${r.date}<small class="sub">${r.time}</small></td><td>${byId(customers, r.customerId).name}</td><td>${byId(drivers, r.driverId).name}</td><td>${r.pickup} → ${r.drop}</td><td>${r.distance.toFixed(1)} km</td><td>${r.status === 'Completed' ? money(r.fare) : '—'}</td><td><span class="tag ${r.status.toLowerCase()}">${r.status}</span></td><td>${r.payment}</td></tr>`).join('');
}
function peakHour(rows) { const counts = group(rows, r => r.time.slice(0, 2)); const top = Object.entries(counts).sort((a, b) => b[1].length - a[1].length)[0]; return top ? `${top[0]}:00` : '—'; }
function renderInsights(completed, cancelled) { const revenue = completed.reduce((s, r) => s + r.fare, 0); const topDriver = Object.entries(group(completed, r => r.driverId)).sort((a, b) => b[1].reduce((s, r) => s + r.fare, 0) - a[1].reduce((s, r) => s + r.fare, 0))[0]; const payment = Object.entries(group(completed, r => r.payment)).sort((a, b) => b[1].reduce((s, r) => s + r.fare, 0) - a[1].reduce((s, r) => s + r.fare, 0))[0]; document.querySelector('#cancel-insight').innerHTML = `<strong>${cancelled.length} cancelled rides</strong><span>${cancelled.length && currentRides.length ? (cancelled.length / currentRides.length * 100).toFixed(1) : '0.0'}% of filtered bookings. Monitor driver availability and waiting times during high-demand periods.</span>`; document.querySelector('#insights-list').innerHTML = [`Total completed-ride revenue is ${money(revenue)}.`, `${topDriver ? byId(drivers, Number(topDriver[0])).name : 'No driver'} is the highest-revenue driver in this view.`, `${peakHour(currentRides)} is the peak booking hour in the filtered dataset.`, `${payment ? payment[0] : 'No payment method'} leads completed-ride revenue.`].map((text, i) => `<div class="insight-item"><b>0${i + 1}</b><span>${text}</span></div>`).join(''); }
function chart(id, config) { if (state.charts[id]) state.charts[id].destroy(); state.charts[id] = new Chart(document.querySelector(`#${id}`), { ...config, options: { responsive: true, maintainAspectRatio: false, plugins: { legend: { display: config.type === 'doughnut', position: 'bottom', labels: { usePointStyle: true, boxWidth: 8, font: { family: 'Manrope' } } }, tooltip: { callbacks: { label: context => ` ${context.dataset.label || ''}: ${context.parsed.y ?? context.raw}` } } }, scales: config.type === 'doughnut' ? {} : { x: { grid: { display: false }, ticks: { color: '#7e8886', font: { family: 'DM Mono' } } }, y: { beginAtZero: true, grid: { color: '#e9eeeb' }, ticks: { color: '#7e8886', font: { family: 'DM Mono' } } } } } }); }
function renderCharts(rows, completed) { const months = ['Jan', 'Feb', 'Mar', 'Apr']; const monthly = months.map((_, i) => completed.filter(r => r.date.slice(5, 7) === String(i + 1).padStart(2, '0')).reduce((s, r) => s + r.fare, 0)); chart('revenue-chart', { type: 'line', data: { labels: months, datasets: [{ label: 'Revenue', data: monthly, borderColor: '#1f8f68', backgroundColor: 'rgba(31,143,104,.12)', fill: true, tension: .35 }] } }); const statuses = ['Completed', 'Cancelled']; chart('status-chart', { type: 'doughnut', data: { labels: statuses, datasets: [{ data: statuses.map(s => rows.filter(r => r.status === s).length), backgroundColor: ['#1f8f68', '#ed765f'], borderWidth: 0 }] } }); const payments = ['UPI', 'Card', 'Cash']; chart('payment-chart', { type: 'bar', data: { labels: payments, datasets: [{ label: 'Revenue', data: payments.map(p => completed.filter(r => r.payment === p).reduce((s, r) => s + r.fare, 0)), backgroundColor: ['#1f8f68', '#2d6cdf', '#e5a63b'], borderRadius: 3, barThickness: 28 }] } }); const driverData = drivers.map(d => completed.filter(r => r.driverId === d.id).reduce((s, r) => s + r.fare, 0)).sort((a, b) => b - a); const driverLabels = drivers.map(d => d.name).sort((a, b) => driverData[drivers.findIndex(d => d.name === b)] - driverData[drivers.findIndex(d => d.name === a)]); chart('driver-chart', { type: 'bar', data: { labels: driverLabels, datasets: [{ label: 'Revenue', data: driverLabels.map(name => completed.filter(r => byId(drivers, drivers.find(d => d.name === name).id)).reduce((s, r) => s + r.fare, 0)), backgroundColor: '#1f8f68', borderRadius: 3 }] } }); const hours = Array.from({ length: 17 }, (_, i) => String(i + 6).padStart(2, '0')); chart('hour-chart', { type: 'bar', data: { labels: hours, datasets: [{ label: 'Rides', data: hours.map(h => rows.filter(r => r.time.startsWith(h)).length), backgroundColor: '#e5a63b', borderRadius: 3, barThickness: 12 }] } }); chart('trend-chart', { type: 'line', data: { labels: months, datasets: [{ label: 'Bookings', data: months.map((_, i) => rows.filter(r => r.date.slice(5, 7) === String(i + 1).padStart(2, '0')).length), borderColor: '#2d6cdf', backgroundColor: 'rgba(45,108,223,.12)', fill: true, tension: .35 }] } }); chart('cancel-chart', { type: 'bar', data: { labels: Object.keys(group(rows.filter(r => r.status === 'Cancelled'), r => byId(customers, r.customerId).city)), datasets: [{ label: 'Cancellations', data: Object.values(group(rows.filter(r => r.status === 'Cancelled'), r => byId(customers, r.customerId).city)).map(x => x.length), backgroundColor: '#ed765f', borderRadius: 3 }] } }); }
function exportCsv() { const header = ['Ride ID', 'Date', 'Time', 'Customer', 'Driver', 'Pickup', 'Drop', 'Distance KM', 'Fare', 'Status', 'Payment']; const body = currentRides.map(r => [r.id, r.date, r.time, byId(customers, r.customerId).name, byId(drivers, r.driverId).name, r.pickup, r.drop, r.distance, r.fare, r.status, r.payment]); const csv = [header, ...body].map(row => row.map(value => `"${String(value).replaceAll('"', '""')}"`).join(',')).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); link.download = 'uber-ride-analytics.csv'; link.click(); }

document.addEventListener('DOMContentLoaded', () => { [...new Set(customers.map(c => c.city))].sort().forEach(city => document.querySelector('#city-filter').insertAdjacentHTML('beforeend', `<option>${city}</option>`)); document.querySelectorAll('.filters select, .filters input').forEach(input => input.addEventListener('change', render)); document.querySelector('#ride-search').addEventListener('input', event => { state.search = event.target.value; renderTables(currentRides.filter(r => r.status === 'Completed')); }); document.querySelector('#clear-filters').addEventListener('click', () => { document.querySelector('#from-date').value = '2025-01-01'; document.querySelector('#to-date').value = '2025-04-30'; document.querySelectorAll('.filters select').forEach(select => select.value = 'all'); render(); }); document.querySelector('#export-btn').addEventListener('click', exportCsv); document.querySelector('#menu-toggle').addEventListener('click', () => document.querySelector('.sidebar').classList.toggle('open')); render(); });